module.exports.heads = {
	home: {
		title: "Home Page - INRL",
		description: "Welcome to INRL, your one-stop online shop for shoes, watches, and gadgets in Kerala.",
		ogTitle: "Home Page - INRL",
		ogDescription: "Discover the latest shoes, watches, and gadgets at INRL. Shop now and enjoy great deals!",
		ogType: "website",
		ogUrl: "https://www.inrl.online/",
		ogImage: "https://www.inrl.online/icon/logo.png",
		ogSiteName: "INRL",
		twitterTitle: "Home Page - INRL",
		twitterDescription: "Explore a wide range of shoes, watches, and gadgets at INRL. Shop the latest trends now!",
		twitterImage: "https://www.inrl.online/icon/logo.png",
		canonicalUrl: "https://www.inrl.online/",
		appleTouchIcon: "https://www.inrl.online/icon/apple-touch-icon.png",
		favicon: "https://www.inrl.online/icon/favicon.ico",
		shortcutIcon: "https://www.inrl.online/icon/favicon.ico",
		maskIcon: "https://www.inrl.online/icon/safari-pinned-tab.svg",
		themeColor: "#ffffff"
	},
	login: {
		title: "Login - INRL",
		description: "Login to access your INRL account and shop for the latest shoes, watches, and gadgets.",
		ogTitle: "Login - INRL",
		ogDescription: "Securely login to your INRL account to continue shopping for shoes, watches, and gadgets.",
		ogType: "website",
		ogUrl: "https://www.inrl.online/login",
		ogImage: "https://www.inrl.online/images/logo.png",
		ogSiteName: "INRL",
		twitterTitle: "Login - INRL",
		twitterDescription: "Access your INRL account to shop for the best deals on shoes, watches, and gadgets.",
		twitterImage: "https://www.inrl.online/icon/logo.png",
		canonicalUrl: "https://www.inrl.online/login",
		appleTouchIcon: "https://www.inrl.online/icon/apple-touch-icon.png",
		favicon: "https://www.inrl.online/icon/favicon.ico",
		shortcutIcon: "https://www.inrl.online/icon/favicon.ico",
		maskIcon: "https://www.inrl.online/icon/safari-pinned-tab.svg",
		themeColor: "#ffffff"
	},
	register: {
		title: "Register - INRL",
		description: "Register your INRL account to securely access shopping features.",
		ogTitle: "Register - INRL",
		ogDescription: "Create your INRL account to ensure secure access to our shopping platform.",
		ogType: "website",
		ogUrl: "https://www.inrl.online/register",
		ogImage: "https://www.inrl.online/icon/logo.png",
		ogSiteName: "INRL",
		twitterTitle: "Register - INRL",
		twitterDescription: "Create your INRL account for secure access to shopping for shoes, watches, and gadgets.",
		twitterImage: "https://www.inrl.online/icon/logo.png",
		canonicalUrl: "https://www.inrl.online/register",
		appleTouchIcon: "https://www.inrl.online/icon/apple-touch-icon.png",
		favicon: "https://www.inrl.online/icon/favicon.ico",
		shortcutIcon: "https://www.inrl.online/icon/favicon.ico",
		maskIcon: "https://www.inrl.online/icon/safari-pinned-tab.svg",
		themeColor: "#ffffff"
	}
};
